spring:
  application:
    name: restaurant-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.iglezaprcevbzjldkutb.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: MLshZRv51jdYvLhF
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8087

cors:
  allowed-origins: "*"