spring:
  application:
    name: restaurant-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.iglezaprcevbzjldkutb
    password: MLshZRv51jdYvLhF
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

cors:
  allowed-origins: "*"