spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&reWriteBatchedInserts=true
    username: postgres.iglezaprcevbzjldkutb
    password: MLshZRv51jdYvLhF
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

cors:
  allowed-origins: "*"

springdoc:
  swagger-ui:
    enabled: true
